### PR TITLE
fix exfo cards

### PR DESCRIPTION
**Pull request by destdev**
various fixes for some exfo cards

### CODE REVIEW

**Comment by destdev** [comment]
summoning him works perfectly fine
keep in mind, the ACTIVATION has to be negated, not just the effect (use cards like solemn to test that)
also, it has to be a monster effect activated on the monster zone on the side of the player who wants to summon it

**Comment by AlphaKretin** [comment]
I was using Solemn Strike, in my test it was the effect of Excode Talker to disable monster zones. Perhaps being in the Extra Monster Zone has something to do with it?

**Comment by Gideon9212** [comment]
@destdev Are you looking at our link proc before applying link type fixs?
We do use diff functions then fluo's so some of their scripts won't work.
https://github.com/Gideon9212/Server_Script_CDB/blob/master/script/proc_link.lua

**Comment by destdev** [comment]
I've looked at the link proc, the parameters for that seem to be the same in both repos. Also, leaving maxc at nil might result in interesting results when looking closer at the code ... I'd say it's better to have a value in there than nil if you compare it with an actual number at one point (if mustg:GetCount()>maxc[...])

**Comment by larry126** [comment]
I am not sure whether removing the c:IsDiscardable(REASON_EFFECT) in the filter of Archfiend's Call is a good idea. I am aware of that in the current card pool, perhaps no cards are able to do such a thing (stop discarding by effect), but for the sake of future cards as well as custom cards, I strongly suggest to keep the check there.

**Comment by AndreOliveiraMendes** [comment]
mustg is for dancing C @destdev, and if it seted to nil, the maxc will be seted to current link value wich is theoricaly max amount, if you don't believe me, take a look at that
https://github.com/Gideon9212/Server_Script_CDB/blob/master/script/proc_link.lua#L13

**Comment by destdev** [comment]
ok, I see what you both mean, I'll correct that

**Comment by AndreOliveiraMendes** [comment]
anway, aparent everything seems fine, for future references lcheck have 3 param

**Comment by Gideon9212** [comment]
Looks good. Thanks!

**Pull request merged**
